x-env-common: &env-common
  APPLICATION_ENVIRONMENT: development
  APPLICATION_DEBUG: 1
  CONFIG_SHARED_PATH: /shared

x-env-api: &env-api
  <<: *env-common
  CONFIG_PROJECT_ROOT: /api

x-env-shared: &env-shared
  <<: *env-common
  CONFIG_PROJECT_ROOT: /shared

x-env-tools: &env-tools
  <<: *env-common
  CONFIG_PROJECT_ROOT: /tools

x-env-ui: &env-ui
  <<: *env-common
  CONFIG_PROJECT_ROOT: /ui

x-api-common: &api-common
  networks:
    - app-network

x-ui-common: &ui-common
  networks:
    - app-network

services:
  api-nginx:
    <<: *api-common
    environment:
      <<: *env-api
    build:
      context: .
      dockerfile: docker/development/nginx/Dockerfile
      args:
        SERVICE_NAME: api
        NGINX_ROOT: /api/public
        PHP_FPM_HOST: api-php-fpm
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8443:443"
    volumes:
      - ./api:/api
      - ./shared:/shared
    depends_on:
      - api-php-fpm
  api-php-fpm:
    <<: *api-common
    environment:
      <<: *env-api
    build:
      context: .
      dockerfile: docker/development/php-fpm/Dockerfile
      args:
        SERVICE_NAME: api
    volumes:
      - ./api:/api
      - ./shared:/shared
  api-php-cli:
    <<: *api-common
    environment:
      <<: *env-api
    build:
      context: .
      dockerfile: docker/development/php-cli/Dockerfile
      args:
        SERVICE_NAME: api
    volumes:
      - ./api:/api
      - ./shared:/shared
  shared-php-cli:
    environment:
      <<: *env-shared
    networks:
      - app-network
    build:
      context: .
      dockerfile: docker/development/php-cli/Dockerfile
      args:
        SERVICE_NAME: shared
    volumes:
      - ./shared:/shared
      - ./tools:/tools
  tools-php-cli:
    environment:
      <<: *env-tools
    networks:
      - app-network
    build:
      context: .
      dockerfile: docker/development/php-cli/Dockerfile
      args:
        SERVICE_NAME: tools
    volumes:
      - ./tools:/tools
  ui-php-cli:
    environment:
      <<: *env-ui
    networks:
      - app-network
    build:
      context: .
      dockerfile: docker/development/php-cli/Dockerfile
      args:
        SERVICE_NAME: ui
    volumes:
      - ./ui:/ui
      - ./shared:/shared
  ui-nginx:
    <<: *ui-common
    environment:
      <<: *env-ui
    build:
      context: .
      dockerfile: docker/development/nginx/Dockerfile
      args:
        SERVICE_NAME: ui
        NGINX_ROOT: /ui/public
        PHP_FPM_HOST: ui-php-fpm
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    volumes:
      - ./ui:/ui
      - ./shared:/shared
    depends_on:
      - ui-php-fpm
  ui-php-fpm:
    <<: *ui-common
    environment:
      <<: *env-ui
    build:
      context: .
      dockerfile: docker/development/php-fpm/Dockerfile
      args:
        SERVICE_NAME: ui
    volumes:
      - ./ui:/ui
      - ./shared:/shared
networks:
  app-network:
    driver: bridge