x-php-common: &php-common
  environment:
    APPLICATION_ENVIRONMENT: development
    APPLICATION_DEBUG: 1
  networks:
    - app-network
services:
  api-nginx:
    build:
      context: .
      dockerfile: docker/development/nginx/Dockerfile
      args:
        SERVICE_NAME: api
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    volumes:
      - ./api:/api
    networks:
      - app-network
    depends_on:
      - api-php-fpm
  api-php-fpm:
    <<: *php-common
    build:
      context: .
      dockerfile: docker/development/php-fpm/Dockerfile
      args:
        SERVICE_NAME: api
    volumes:
      - ./api:/api
  api-php-cli:
    <<: *php-common
    build:
      context: .
      dockerfile: docker/development/php-cli/Dockerfile
      args:
        SERVICE_NAME: api
    volumes:
      - ./api:/api
  shared-php-cli:
    <<: *php-common
    build:
      context: .
      dockerfile: docker/development/php-cli/Dockerfile
      args:
        SERVICE_NAME: shared
    volumes:
      - ./shared:/shared
      - ./tools:/tools
  tools-php-cli:
    <<: *php-common
    build:
      context: .
      dockerfile: docker/development/php-cli/Dockerfile
      args:
        SERVICE_NAME: tools
    volumes:
      - ./tools:/tools
  ui-php-cli:
    <<: *php-common
    build:
      context: .
      dockerfile: docker/development/php-cli/Dockerfile
      args:
        SERVICE_NAME: ui
    volumes:
      - ./ui:/ui
networks:
  app-network:
    driver: bridge